INSERT INTO provider (id, name, site_url, data_url, mechanism, logo, cron_expression, params, active)
VALUES (nextval('provider_seq'), 'Oliveira Imóveis', 'https://www.oliveiraimoveissm.com.br', 'https://www.oliveiraimoveissm.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Fernando Flores', 'https://www.fernandoflores.com.br', 'https://www.fernandoflores.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Toneto Empreendimentos', 'https://www.tonetoempreendimentos.com.br',
        'https://www.tonetoempreendimentos.com.br/imoveis/a-venda/', 'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Hanover Imobiliária', 'https://www.imobiliariahanover.com.br', 'https://www.imobiliariahanover.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Zimbro Imóveis', 'https://www.zimbroimoveis.com.br', 'https://www.zimbroimoveis.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Banco de Imóveis', 'https://www.bancodeimoveis.net', 'https://www.bancodeimoveis.net/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Cancian Imóveis', 'https://cancianimoveis.com.br', 'https://d3gy91ixuib5mq.cloudfront.net/', 'UNIVERSAL_SOFTWARE', null,
        '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Café Imobiliária', 'https://www.cafeimobiliaria.com.br', 'https://www.cafeimobiliaria.com.br/jsons/', 'SUPER_LOGICA', null,
        '0 0 9 ? * MON,WED,FRI *', '{"jsonFile":"cafeimoveis.json"}', 'N'),
       (nextval('provider_seq'), 'Maiquel Oliveira', 'https://maiqueloliveira.com.br', null, 'JETIMOB_V2', null,
        '0 0 9 ? * MON,WED,FRI *', '{"subTypes":["Apartamento","Casa","Casa de Condomínio","Cobertura","Sobrado","Terreno"]}', 'N'),
       (nextval('provider_seq'), 'Imobiliária Modelo', 'https://www.imobiliariamodelosm.com.br', 'https://www.imobiliariamodelosm.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Jair Behr Imóveis', 'https://www.jairbehr.com.br', 'https://www.jairbehr.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Santa Imóveis', 'https://www.santaimoveissm.com.br', 'https://www.santaimoveissm.com.br/imoveis/a-venda/', 'JETIMOB_V1', null,
        '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Saul Souza Imóveis', 'https://www.saulsouzaimoveis.com.br', 'https://www.saulsouzaimoveis.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Imobiliária Cruzeiro', 'https://www.imobiliariacruzeiro.com.br',
        'https://www.imobiliariacruzeiro.com.br/imoveis/a-venda/', 'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Noro Imóveis', 'https://www.noroimoveis.com.br', 'https://www.noroimoveis.com.br/imoveis/a-venda/', 'JETIMOB_V1', null,
        '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Letícia Imóveis', 'https://www.leticiaimoveis.com.br', 'https://www.leticiaimoveis.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Bellagio Imóveis', 'https://www.bellagioimoveis.com.br',
        'https://www.bellagioimoveis.com.br/imoveis/a-venda/', 'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Luiz Coelho Imóveis', 'https://www.luizcoelhoimoveis.com.br', null, 'JETIMOB_V3', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'InVista Imóveis', 'https://www.invistaimoveissm.com.br', 'https://www.invistaimoveissm.com.br', 'ALAN_WGT', null,
        '0 0 9 ? * MON,WED,FRI *', '{"hash":"SMJNq9M_zibwamhVExL-Z"}', 'N'),
       (nextval('provider_seq'), 'Cotrel Imóveis', 'https://www.cotrelimoveis.com.br', null, 'JETIMOB_V4', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Itaimbé Imóveis', 'https://www.itaimbeimoveis.com.br', null, 'JETIMOB_V4', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Bravier Imóveis', 'https://www.bravier.com.br', null, 'JETIMOB_V4', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Soma Imobiliária', 'https://www.somaimobiliaria.com.br', null, 'JETIMOB_V4', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'JK Imóveis', 'https://www.jkimoveis.com.br', 'https://www.jkimoveis.com.br/imoveis/a-venda/', 'JETIMOB_V1', null,
        '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Almeida Imóveis', 'https://www.almeidaimoveissm.com.br', 'https://www.almeidaimoveissm.com.br/imoveis/a-venda/', 'JETIMOB_V1',
        null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Proprieta Imóveis', 'https://www.proprietaimoveis.com.br', 'https://www.proprietaimoveis.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Estrutura Imóveis', 'https://www.estruturaimoveissm.com.br', 'https://www.estruturaimoveissm.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Altra Imóveis', 'https://www.altraimoveis.com.br', 'https://www.altraimoveis.com.br/imoveis/a-venda/', 'JETIMOB_V1', null,
        '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Correta Imóveis', 'https://www.corretaimoveissm.com.br', 'https://www.corretaimoveissm.com.br/imoveis/a-venda/', 'JETIMOB_V1',
        null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Vend Imóveis', 'https://www.vendsm.com.br', 'https://www.vendsm.com.br/imoveis/a-venda/', 'JETIMOB_V1', null,
        '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Prisma Imóveis', 'https://www.prismaimoveis.com', 'https://www.prismaimoveis.com/imoveis/a-venda/', 'JETIMOB_V1', null,
        '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Imobiliária Salazar', 'https://www.imobiliariasalazar.com.br', 'https://www.imobiliariasalazar.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Plazza Imóveis', 'https://www.plazzaimoveis.com.br', null, 'JETIMOB_V4', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Reside Imóveis', 'https://www.resideimoveissm.com.br', 'https://www.resideimoveissm.com.br/imoveis/a-venda/', 'JETIMOB_V1',
        null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Amilton Júnior Negócios Imobiliários', 'https://www.amiltonjunior.com.br',
        'https://www.amiltonjunior.com.br/imoveis/a-venda/', 'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Pró Imóveis', 'https://www.proimoveissm.com.br', 'https://www.proimoveissm.com.br/imoveis/a-venda/', 'JETIMOB_V1', null,
        '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Ideal Imóveis', 'https://www.idealsm.com.br', 'https://www.idealsm.com.br/imoveis/a-venda/', 'JETIMOB_V1', null,
        '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Scremin Imóveis', 'https://www.imobiliariaquadrosescremin.com.br',
        'https://www.imobiliariaquadrosescremin.com.br/imoveis/a-venda/', 'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Patrick Portela Imóveis', 'https://www.patrickportella.com.br', 'https://www.patrickportella.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Imobiliária Casa Sul', 'https://www.casasulimoveis.com.br', 'https://www.casasulimoveis.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Select Investimentos Imobiliários', 'https://www.selectaimoveissm.com.br',
        'https://www.selectaimoveissm.com.br/imoveis/a-venda/', 'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Predial Imóveis', 'https://www.predialsm.com.br', 'https://www.predialsm.com.br/imoveis/a-venda/', 'JETIMOB_V1', null,
        '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Jetlar', 'https://www.jetlar.com', null, 'JETIMOB_V4', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Pellenz Assessoria Imobiliária', 'https://www.pellenzassessoria.com.br',
        'https://www.pellenzassessoria.com.br/imoveis/a-venda/', 'JETIMOB_V1', null,
        '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Paulo Coelho Imóveis', 'https://www.paulocoelhoimoveis.com.br', 'https://www.paulocoelhoimoveis.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Habitalar Imóveis', 'https://www.habitalarimoveis.com.br', 'https://www.habitalarimoveis.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Invest-SM Assessoria Imobiliária', 'https://www.investimoveissm.com.br',
        'https://www.investimoveissm.com.br/imoveis/a-venda/', 'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Morcelli Imóveis', 'https://www.morcelliimoveis.com.br/', null, 'JETIMOB_V4', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Inovar Imóveis', 'https://www.inovarimoveissm.com.br', 'https://www.inovarimoveissm.com.br/imoveis/a-venda/', 'JETIMOB_V1',
        null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Roma Imóveis', 'https://www.romaimoveissm.com.br', 'https://www.romaimoveissm.com.br/imoveis/a-venda/', 'JETIMOB_V1', null,
        '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Rio Branco Imóveis', 'https://www.riobrancoimoveissm.com.br', 'https://www.riobrancoimoveissm.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Imovest', 'https://www.imovestsm.com.br', 'https://www.imovestsm.com.br/imoveis/a-venda/', 'JETIMOB_V1', null,
        '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Conceição Imóveis', 'https://www.conceicaoimoveissm.com.br', 'https://www.conceicaoimoveissm.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Casamata Imóveis', 'https://www.casamataimoveis.com.br', 'https://www.casamataimoveis.com.br/imoveis/a-venda/', 'JETIMOB_V1',
        null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Catiane Lange Soluções Imobiliárias', 'https://www.catianelange.com.br', 'https://www.catianelange.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Coase Imobiliária', 'https://www.imobiliariacoase.com.br', 'https://www.imobiliariacoase.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Righi Imobiliária', 'https://www.imobiliariarighi.com.br/', null, 'JETIMOB_V4', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Amalfi Dashboard Group', 'https://www.amalfihome.com.br', 'https://www.amalfihome.com.br/imoveis/a-venda/', 'JETIMOB_V1',
        null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Arigony Imóveis', 'https://www.arigonyimoveis.com', 'https://www.arigonyimoveis.com/imoveis/a-venda/', 'JETIMOB_V1', null,
        '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Jobim Imóveis', 'https://www.jobimimoveis.com.br', 'https://www.jobimimoveis.com.br/imoveis/a-venda/', 'JETIMOB_V1', null,
        '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Fiduccia Imóveis', 'https://www.fiducciaimoveis.com.br', 'https://www.fiducciaimoveis.com.br/imoveis/a-venda/', 'JETIMOB_V1',
        null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Douglas Maia Imóveis', 'https://www.douglasmaiaimoveis.com.br', 'https://www.douglasmaiaimoveis.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Cobertura Imóveis', 'https://www.coberturacorretora.com.br', 'https://www.coberturacorretora.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'CK Investimentos', 'https://www.cekinvestimentos.com.br', 'https://www.cekinvestimentos.com.br/imoveis/a-venda/',
        'JETIMOB_V1', null, '0 0 9 ? * MON,WED,FRI *', null, 'N'),
       (nextval('provider_seq'), 'Prize Imóveis', 'https://www.imoveisprize.com.br', 'https://www.imoveisprize.com.br/imoveis/a-venda/', 'JETIMOB_V1', null,
        '0 0 9 ? * MON,WED,FRI *', null, 'N');
