name: Java dependency check
on:
  workflow_run:
    workflows: [ "Java unit tests" ]
    branches: [ "*" ]
    types:
      - completed
jobs:
  job:
    name: Maven dependency check
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Prepare NVD OWASP cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: ${{ runner.os }}-nvd-owasp
          restore-keys: ${{ runner.os }}-nvd-owasp

      - name: Mvn dependency-check:aggregate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -DnvdApiKey=${{ secrets.NVD_API_KEY }} -B -DskipTests package dependency-check:aggregate

      - name: Upload dependency check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html
