# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Java CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      - name: Deleting Previous JaCoCo Cache
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete "commons-jacoco-report" --confirm
          gh actions-cache delete "commons-rest-jacoco-report" --confirm
          gh actions-cache delete "commons-scraper-jacoco-report" --confirm
          gh actions-cache delete "commons-messaging-jacoco-report" --confirm
          gh actions-cache delete "jetimob-scraper-jacoco-report" --confirm
          gh actions-cache delete "data-jacoco-report" --confirm

      - name: Caching Commons Jacoco Report
        uses: actions/cache@v4
        with:
          path: commons/target/site/jacoco
          key: commons-jacoco-report

      - name: Caching Commons Rest Jacoco Report
        uses: actions/cache@v4
        with:
          path: commons-rest/target/site/jacoco
          key: commons-rest-jacoco-report

      - name: Caching Commons Scraper Jacoco Report
        uses: actions/cache@v4
        with:
          path: commons-scraper/target/site/jacoco
          key: commons-scraper-jacoco-report

      - name: Caching Commons Messaging Jacoco Report
        uses: actions/cache@v4
        with:
          path: commons-messaging/target/site/jacoco
          key: commons-messaging-jacoco-report

      - name: Caching Jetimob Scraper Jacoco Report
        uses: actions/cache@v4
        with:
          path: jetimob-scraper/target/site/jacoco
          key: jetimob-scraper-jacoco-report

      - name: Caching Data Jacoco Report
        uses: actions/cache@v4
        with:
          path: data/target/site/jacoco
          key: data-jacoco-report

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: "**/target/surefire-reports/*.xml"
          fail_if_no_tests: false
          check_name: Surefire Test Report
          github_token: ${{ secrets.GITHUB_TOKEN }}

  coverage:
    name: Code Coverage
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restoring Cached Commons Jacoco Report
        uses: actions/cache/restore@v4
        with:
          path: commons/target/site/jacoco
          key: commons-jacoco-report

      - name: Generate JaCoCo Badge - Commons
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: commons/target/site/jacoco/jacoco.csv
          coverage-badge-filename: commons-coverage-jacoco.svg
          branches-badge-filename: commons-branches-jacoco.svg
          workflow-summary-heading: Module Commons - JaCoCo Test Coverage Summary

      - name: Restoring Cached Commons Rest Jacoco Report
        uses: actions/cache/restore@v4
        with:
          path: commons-rest/target/site/jacoco
          key: commons-rest-jacoco-report

      - name: Generate JaCoCo Badge - Commons Rest
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: commons-rest/target/site/jacoco/jacoco.csv
          coverage-badge-filename: commons-rest-coverage-jacoco.svg
          branches-badge-filename: commons-rest-branches-jacoco.svg
          workflow-summary-heading: Module Commons Rest - JaCoCo Test Coverage Summary

      - name: Restoring Cached Commons Scraper Jacoco Report
        uses: actions/cache/restore@v4
        with:
          path: commons-scraper/target/site/jacoco
          key: commons-scraper-jacoco-report

      - name: Generate JaCoCo Badge - Commons Scraper
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: commons-scraper/target/site/jacoco/jacoco.csv
          coverage-badge-filename: commons-scraper-coverage-jacoco.svg
          branches-badge-filename: commons-scraper-branches-jacoco.svg
          workflow-summary-heading: Module Commons Scraper - JaCoCo Test Coverage Summary

      - name: Restoring Commons Messaging Jacoco Report
        uses: actions/cache/restore@v4
        with:
          path: commons-messaging/target/site/jacoco
          key: commons-messaging-jacoco-report

      - name: Generate JaCoCo Badge - Commons Messaging
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: commons-messaging/target/site/jacoco/jacoco.csv
          coverage-badge-filename: commons-messaging-coverage-jacoco.svg
          branches-badge-filename: commons-messaging-branches-jacoco.svg
          workflow-summary-heading: Module Commons Messaging - JaCoCo Test Coverage Summary

      - name: Restoring Jetimob Scraper Jacoco Report
        uses: actions/cache/restore@v4
        with:
          path: jetimob-scraper/target/site/jacoco
          key: jetimob-scraper-jacoco-report

      - name: Generate JaCoCo Badge - Jetimob Scraper
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: jetimob-scraper/target/site/jacoco/jacoco.csv
          coverage-badge-filename: jetimob-scraper-coverage-jacoco.svg
          branches-badge-filename: jetimob-scraper-branches-jacoco.svg
          workflow-summary-heading: Module Jetimob Scraper - JaCoCo Test Coverage Summary

      - name: Restoring Data Jacoco Report
        uses: actions/cache/restore@v4
        with:
          path: data/target/site/jacoco
          key: data-jacoco-report

      - name: Generate JaCoCo Badge - Data
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: data/target/site/jacoco/jacoco.csv
          coverage-badge-filename: data-coverage-jacoco.svg
          branches-badge-filename: data-branches-jacoco.svg
          workflow-summary-heading: Module Data - JaCoCo Test Coverage Summary

      - name: JoCoco Badge Commit
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Thiago Gomes Borba'
            git config --global user.email 'thiago.borba@users.noreply.github.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language:
          - java
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: +security-and-quality

      - name: Build with Maven
        run: mvn -B -DskipTests package --file pom.xml

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  sonarcloud:
    name: Sonarcloud Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar