name: Java unit tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]
jobs:
  job:
    name: Maven package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Mvn clean package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B clean package

      - name: Update dependency graph
        if: github.event_name != 'pull_request'
        uses: advanced-security/maven-dependency-submission-action@v4

      - name: Publish surefire test report
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: "**/target/surefire-reports/*.xml"
          fail_if_no_tests: false
          check_name: Surefire Test Report
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "commons: generate jacoco badge"
        uses: cicirello/jacoco-badge-generator@v2
        if: github.event_name != 'pull_request'
        with:
          generate-branches-badge: true
          jacoco-csv-file: commons/target/site/jacoco/jacoco.csv
          coverage-badge-filename: commons-coverage-jacoco.svg
          branches-badge-filename: commons-branches-jacoco.svg
          workflow-summary-heading: Module Commons - JaCoCo Test Coverage Summary

      - name: "commons-rest: generate jacoco badge"
        uses: cicirello/jacoco-badge-generator@v2
        if: github.event_name != 'pull_request'
        with:
          generate-branches-badge: true
          jacoco-csv-file: commons-rest/target/site/jacoco/jacoco.csv
          coverage-badge-filename: commons-rest-coverage-jacoco.svg
          branches-badge-filename: commons-rest-branches-jacoco.svg
          workflow-summary-heading: Module Commons Rest - JaCoCo Test Coverage Summary

      - name: "commons-scraper: generate jacoco badge"
        uses: cicirello/jacoco-badge-generator@v2
        if: github.event_name != 'pull_request'
        with:
          generate-branches-badge: true
          jacoco-csv-file: commons-scraper/target/site/jacoco/jacoco.csv
          coverage-badge-filename: commons-scraper-coverage-jacoco.svg
          branches-badge-filename: commons-scraper-branches-jacoco.svg
          workflow-summary-heading: Module Commons Scraper - JaCoCo Test Coverage Summary

      - name: "commons-messaging: generate jacoco badge"
        uses: cicirello/jacoco-badge-generator@v2
        if: github.event_name != 'pull_request'
        with:
          generate-branches-badge: true
          jacoco-csv-file: commons-messaging/target/site/jacoco/jacoco.csv
          coverage-badge-filename: commons-messaging-coverage-jacoco.svg
          branches-badge-filename: commons-messaging-branches-jacoco.svg
          workflow-summary-heading: Module Commons Messaging - JaCoCo Test Coverage Summary

      - name: "commons-grpc: generate jacoco badge"
        uses: cicirello/jacoco-badge-generator@v2
        if: github.event_name != 'pull_request'
        with:
          generate-branches-badge: true
          jacoco-csv-file: commons-grpc/target/site/jacoco/jacoco.csv
          coverage-badge-filename: commons-grpc-coverage-jacoco.svg
          branches-badge-filename: commons-grpc-branches-jacoco.svg
          workflow-summary-heading: Module Commons GRPC - JaCoCo Test Coverage Summary

      - name: "commons-jetimob-scraper: generate jacoco badge"
        uses: cicirello/jacoco-badge-generator@v2
        if: github.event_name != 'pull_request'
        with:
          generate-branches-badge: true
          jacoco-csv-file: jetimob-scraper/target/site/jacoco/jacoco.csv
          coverage-badge-filename: jetimob-scraper-coverage-jacoco.svg
          branches-badge-filename: jetimob-scraper-branches-jacoco.svg
          workflow-summary-heading: Module Jetimob Scraper - JaCoCo Test Coverage Summary

      - name: "data: generate jacoco badge"
        uses: cicirello/jacoco-badge-generator@v2
        if: github.event_name != 'pull_request'
        with:
          generate-branches-badge: true
          jacoco-csv-file: data/target/site/jacoco/jacoco.csv
          coverage-badge-filename: data-coverage-jacoco.svg
          branches-badge-filename: data-branches-jacoco.svg
          workflow-summary-heading: Module Data - JaCoCo Test Coverage Summary

      - name: "api: generate jacoco badge"
        uses: cicirello/jacoco-badge-generator@v2
        if: github.event_name != 'pull_request'
        with:
          generate-branches-badge: true
          jacoco-csv-file: api/target/site/jacoco/jacoco.csv
          coverage-badge-filename: api-coverage-jacoco.svg
          branches-badge-filename: api-branches-jacoco.svg
          workflow-summary-heading: Module API - JaCoCo Test Coverage Summary

      - name: git commit jacoco badges
        if: github.event_name != 'pull_request'
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Thiago Gomes Borba'
            git config --global user.email 'thiago.borba@users.noreply.github.com'
            git add -A
            git commit -m "Push unit tests badges"
            git push
          fi

      - name: Zip modules target folder
        run: zip -r maven-target.zip **/target/

      - name: Caching modules targets
        uses: actions/cache/save@v4
        with:
          path: maven-target.zip
          key: maven-target
