# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Java CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  mavenPackage:
    name: Maven Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -DnvdApiKey=${{ secrets.NVD_API_KEY }} -B package dependency-check:aggregate --file pom.xml

      - name: Upload Dependency Check Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: "**/target/surefire-reports/*.xml"
          fail_if_no_tests: false
          check_name: Surefire Test Report
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate JaCoCo Badge - Commons
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: commons/target/site/jacoco/jacoco.csv
          coverage-badge-filename: commons-coverage-jacoco.svg
          branches-badge-filename: commons-branches-jacoco.svg
          workflow-summary-heading: Module Commons - JaCoCo Test Coverage Summary

      - name: Generate JaCoCo Badge - Commons Rest
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: commons-rest/target/site/jacoco/jacoco.csv
          coverage-badge-filename: commons-rest-coverage-jacoco.svg
          branches-badge-filename: commons-rest-branches-jacoco.svg
          workflow-summary-heading: Module Commons Rest - JaCoCo Test Coverage Summary

      - name: Generate JaCoCo Badge - Commons Scraper
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: commons-scraper/target/site/jacoco/jacoco.csv
          coverage-badge-filename: commons-scraper-coverage-jacoco.svg
          branches-badge-filename: commons-scraper-branches-jacoco.svg
          workflow-summary-heading: Module Commons Scraper - JaCoCo Test Coverage Summary

      - name: Generate JaCoCo Badge - Commons Messaging
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: commons-messaging/target/site/jacoco/jacoco.csv
          coverage-badge-filename: commons-messaging-coverage-jacoco.svg
          branches-badge-filename: commons-messaging-branches-jacoco.svg
          workflow-summary-heading: Module Commons Messaging - JaCoCo Test Coverage Summary

      - name: Generate JaCoCo Badge - Jetimob Scraper
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: jetimob-scraper/target/site/jacoco/jacoco.csv
          coverage-badge-filename: jetimob-scraper-coverage-jacoco.svg
          branches-badge-filename: jetimob-scraper-branches-jacoco.svg
          workflow-summary-heading: Module Jetimob Scraper - JaCoCo Test Coverage Summary

      - name: Generate JaCoCo Badge - Data
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: data/target/site/jacoco/jacoco.csv
          coverage-badge-filename: data-coverage-jacoco.svg
          branches-badge-filename: data-branches-jacoco.svg
          workflow-summary-heading: Module Data - JaCoCo Test Coverage Summary

      - name: JoCoco Badge Commit
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Thiago Gomes Borba'
            git config --global user.email 'thiago.borba@users.noreply.github.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi

  codeQL:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language:
          - java
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: +security-and-quality

      - name: Build with Maven
        run: mvn -B -DskipTests package --file pom.xml

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  sonarCloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --file pom.xml

  dockerBuild:
    name: Docker Build And Push
    runs-on: ubuntu-latest
    needs: mavenPackage
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Compile with Maven
        run: mvn -B compile --file pom.xml

      - name: Build Docker Image Jetimob-Scraper
        run: docker build . --file Dockerfile-jetimob-scraper --tag aquinate/house-seeker-jetimob-scraper:latest

      - name: Build Docker Image Data
        run: docker build . --file Dockerfile-data --tag aquinate/house-seeker-data:latest

      - name: Log into docker.io
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: docker.io
          username: aquinate
          password: ${{ secrets.DOCKER_HUB_PSW }}

      - name: Push Docker Image Jetimob-Scraper
        run: docker push aquinate/house-seeker-jetimob-scraper:latest

      - name: Push Docker Image Data
        run: docker push aquinate/house-seeker-data:latest