name: SonarCloud scanner
on:
  workflow_run:
    workflows: [ "Java unit tests" ]
    branches: [ "*" ]
    types:
      - completed
jobs:
  job:
    name: SonarCloud scanner
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name != 'pull_request' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Prepare sonar cache
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Restoring modules targets
        uses: actions/cache/restore@v4
        with:
          path: maven-target.zip
          key: maven-target

      - name: Unzip module targets
        run: upzip -o maven-target.zip

      - name: Mvn sonar-maven-plugin:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
